//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int InvoiceIDFK { get; set; }
        public int GuestIDFK { get; set; }
        public int RoomIDFK { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int ExtraBeds { get; set; }
        public bool Wifi { get; set; }
        public decimal Bar { get; set; }
        public decimal Phone { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Room Room { get; set; }
    }
}
